### PR TITLE
Adding documentation to the README

### PR DESCRIPTION
**Pull request by bab4379**
This is my first go at a reusable workflow.  I have tested this with my idmms workflows and it is working as expected.  Looking for any suggestions or feedback and whether you think this is worth maintaining.  The steps that add/update comments only work if the event that triggers this is from a pull_request, if it is not triggered by a PR those steps should be skipped as there is no PR to add comments to.

### CODE REVIEW

**Comment by nie7321** [comment]
Two initial thoughts:

- Would this be better as a single-purpose repository? [If you tag an action repo, that version can be referenced in the end-user's workflow](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management). But if this is a multi-purpose repo, every time we bump *any* action in here, we have to make a new tag, and that tag may not be meaningful to some users.

- I would recommend against [defaulting the TF version](https://github.com/NIT-Administrative-Systems/ado-reusable-workflows/blob/main/.github/workflows/terraform-reusable.yml#L14). We're definitely *not* consistent about it across the fleet, so I'd say we should make people take ownership of this.

**Comment by bab4379** [comment]
Changed terraform version to be required, and reflected that change in the documentation.  

I had not thought about versioning.  What would be the ramifications of this, and what is our standard?  I would think we would encourage people to pin to a tagged version instead of the main so they will not be surprised by a breaking change? If we did have a new release would the old releases go away?  Or would it just be confusing to people that there is a new release, but nothing changed to the specific workflow they were using?  

I would be happy to change the name of the repo to make it terraform specific if we think that is best

**Comment by nie7321** [comment]
> What would be the ramifications of this, and what is our standard?

`as-shared-jenkins@master` which causes every single jenkins job we have to rebuild itself if you commit to it, which in turn causes every jenkins server to get stuck since every executor slot is waiting for a slot to free up so it can launch docker and then somebody has to go reboot them ✌️ 

> I would think we would encourage people to pin to a tagged version instead of the main so they will not be surprised by a breaking change?
> . . .
> Or would it just be confusing to people that there is a new release, but nothing changed to the specific workflow they were using?

Yes, it should work just like any other dependency and [use semver](https://semver.org/). Dependabot can detect the action release and open PRs to update your workflows.

I would say the reason to have one repo per action is then it's easier to track what's going on. If we have a changelog and you want to upgrade your TF action, everything in there is applicable. If we have 4 or 5 actions in here, it becomes a lot messier -- which changelog entries are relevant?

I think dependabot posting a changelog in the PR relies on following the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) spec -- which I think makes the assumption you just have one `CHANGELOG.md` at the repo root -- so there's no nice way to break the changlog up so people only see what's relevant to them.

> If we did have a new release would the old releases go away?

Nope, not unless you delete the tag!

**Comment by bab4379** [comment]
Updated to ado-reusable-terraform-workflow.

**Pull request merged**
